paths:
  /api/product/:
    get:
      summary: Obtener todos los productos
      description: Se obtienen todos los productos disponibles.
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos satisfactoriamente de la base de datos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductDetails"
        "400":
          description: El id o alguna propiedad especificada no son válidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response400"
        "404":
          description: El producto no fue encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response404"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response500"
    post:
      summary: Agregar un nuevo producto
      description: Se agrega un nuevo producto a la base de datos.
      security:
        - cookieAuth: []
      tags:
        - Products
      requestBody:
        description: Object del producto a ser agregado a la base de datos.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - description
                - price
                - thumbnails
                - code
                - stock
                - category
              properties:
                title:
                  type: string
                  description: El título del producto.
                description:
                  type: string
                  description: La descripción del producto.
                price:
                  type: number
                  description: El precio del producto.
                thumbnails:
                  type: array
                  items:
                    type: string
                    description: La URL del producto.
                code:
                  type: string
                  description: El código del producto.
                stock:
                  type: number
                  description: El stock del producto.
                category:
                  type: string
                  description: La categoría del producto.
      responses:
        "200":
          description: Producto agregado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Success: Producto agregado"
        "400":
          description: Ocurrió un error al agregar el producto.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response400"
        "401":
          description: No se pudo autenticar el usuario
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response401"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response500"
  /api/product/{pid}:
    get:
      summary: Obtener un producto por ID
      description: Este endpoint permite obtener un producto específico a partir de su ID.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se solicita.
          schema:
            type: string
            example: "6635a4359a91d1aaa6e1fb62"
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: El id o alguna propiedad especificada no son válidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response400"
        "404":
          description: El producto no fue encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response404"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response500"
    put:
      summary: Actualizar un producto a partir de su id
      description: Este endpoint permite actualizar un producto existente en la base de datos.
      security:
        - cookieAuth: []
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se desea actualizar.
          schema:
            type: string
            example: "6635a4359a91d1aaa6e1fb62"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/updateProduct"
      responses:
        "200":
          description: Producto actualizado con éxito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDetails"
        "400":
          description: El id o alguna propiedad especificada no son válidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response400"
        "401":
          description: No se pudo autenticar el usuario
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response401"
        "403":
          description: El usuario no tiene los permisos necesarios
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response403"
        "404":
          description: El producto no fue encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response404"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response500"
    delete:
      summary: Elimina un producto
      description: Esta ruta permite eliminar un producto por su ID.
      security:
        - cookieAuth: []
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a eliminar.
          schema:
            type: string
            example: "6635a4359a91d1aaa6e1fb62"
      responses:
        "200":
          description: El producto fue eliminado con éxito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "401":
          description: No se pudo autenticar el usuario
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response401"
        "403":
          description: El usuario no tiene los permisos necesarios
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response403"
        "404":
          description: El producto no fue encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response404"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response500"